# Generated by Django 4.0.6 on 2022-07-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eventtype', models.CharField(choices=[('', 'Select Event Type'), ('Public Event', 'Public Event'), ('Invites Only', 'Invites Only')], default='', max_length=100)),
                ('eventname', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(upload_to='uploads/')),
                ('date', models.DateField()),
                ('guests', models.CharField(max_length=100)),
            ],
        ),
    ]
