# Generated by Django 4.0.6 on 2022-07-16 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
