# Generated by Django 4.0.6 on 2022-07-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('identificationnumber', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=100)),
                ('county', models.CharField(choices=[('', 'Select County'), ('Kisumu', 'Kisumu'), ('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Siaya', 'Siaya')], default='', max_length=100)),
                ('event_applied_for', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvitedGuests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guesttitle', models.CharField(choices=[('', 'Select Title'), ('Dr.', 'Dr.'), ('Sir', 'Sir'), ('Madam', 'Madam'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], default='', max_length=100)),
                ('guestname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('identificationnumber', models.CharField(max_length=100)),
                ('guestrole', models.CharField(choices=[('', 'Select Role'), ('Guest of Honour', 'Guest of Honour'), ('Main Speaker', 'Main Speaker'), ('Attendee', 'Attendee')], default='', max_length=100)),
                ('contribution', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InvitesOnlyRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('', 'Select Title'), ('Dr.', 'Dr.'), ('Sir', 'Sir'), ('Madam', 'Madam'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], default='', max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('identificationnumber', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=100)),
                ('county', models.CharField(choices=[('', 'Select County'), ('Kisumu', 'Kisumu'), ('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Siaya', 'Siaya')], default='', max_length=100)),
                ('reservation', models.CharField(choices=[('', 'Select Reservation'), ('VVIP', 'VVIP'), ('VIP', 'VIP'), ('Normal', 'Normal')], default='', max_length=100)),
                ('event_applied_for', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('bio', models.CharField(max_length=250)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=250)),
                ('city', models.CharField(choices=[('', 'Select your city'), ('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu')], default='', max_length=250)),
                ('county', models.CharField(choices=[('', 'Select County'), ('Kisumu', 'Kisumu'), ('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Siaya', 'Siaya')], default='', max_length=250)),
                ('religion', models.CharField(choices=[('', 'Select your Religion'), ('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('Bahai', 'Bahai'), ('Jew', 'Jew')], default='', max_length=250)),
            ],
        ),
    ]
