# Generated by Django 4.0.6 on 2022-07-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_remove_profile_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestregistration',
            name='reservation',
            field=models.CharField(choices=[('', 'Select Reservation'), ('VVIP', 'VVIP'), ('VIP', 'VIP'), ('First Class', 'First Class'), ('Economy', 'Economy')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='guestregistration',
            name='title',
            field=models.CharField(choices=[('', 'Select Title'), ('Dr.', 'Dr.'), ('Sir', 'Sir'), ('Madam', 'Madam'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], default='', max_length=100),
        ),
    ]
